import { StyleSheet } from "react-native";

const lightStyles = StyleSheet.create({
    container: { padding: 10, flex: 1, backgroundColor: "#F0F8FF" },
    header: { flexDirection: "row", alignItems: "center", gap: 8 },
    headerText: { color: "black" },
    deliveryInfo: {
      backgroundColor: "white",
      padding: 8,
      marginTop: 15,
      borderRadius: 8,
    },
    deliveryTime: { fontWeight: "500" },
    itemsAdded: { marginVertical: 12 },
    itemsAddedText: {
      textAlign: "center",
      letterSpacing: 3,
      fontSize: 15,
      color: "gray",
    },
    itemContainer: { backgroundColor: "white", padding: 10 },
    itemRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginVertical: 6,
    },
    itemName: { width: 200, fontSize: 16, fontWeight: "600" },
    quantityControl: {
      flexDirection: "row",
      paddingHorizontal: 10,
      paddingVertical: 5,
      alignItems: "center",
      borderColor: "#BEBEBE",
      borderWidth: 0.5,
      borderRadius: 10,
    },
    quantityButton: {
      fontSize: 20,
      color: "green",
      paddingHorizontal: 6,
      fontWeight: "600",
    },
    quantityText: {
      fontSize: 19,
      color: "green",
      paddingHorizontal: 8,
      fontWeight: "600",
    },
    itemPrice: { fontSize: 16, fontWeight: "bold" },
    itemQuantity: { fontSize: 15, fontWeight: "500" },
    deliveryInstructions: { marginVertical: 10 },
    deliveryInstructionsText: { fontSize: 16, fontWeight: "600" },
    instructionContainer: {
      margin: 10,
      borderRadius: 10,
      padding: 10,
      backgroundColor: "white",
    },
    instructionContent: { justifyContent: "center", alignItems: "center" },
    instructionText: {
      width: 75,
      fontSize: 13,
      color: "#383838",
      paddingTop: 10,
      textAlign: "center",
    },
    additionalOptions: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      backgroundColor: "white",
      paddingVertical: 10,
      paddingHorizontal: 10,
    },
    optionRow: { flexDirection: "row", alignItems: "center", gap: 6 },
    optionText: { color: "black" },
    donationContainer: {
      padding: 10,
      backgroundColor: "white",
      marginVertical: 10,
    },
    donationRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    donationText: { color: "black" },
    donationDescription: { color: "gray" },
    donationAmount: { color: "black" },
    billingDetails: { marginVertical: 10 },
    billingDetailsText: { fontSize: 16, fontWeight: "bold" },
    billingContainer: {
      backgroundColor: "white",
      borderRadius: 7,
      padding: 10,
      marginTop: 14,
    },
    billingRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    billingLabel: { fontSize: 15, fontWeight: "400", color: "#505050" },
    billingValue: { fontSize: 15, fontWeight: "400", color: "#505050" },
    billingTotalLabel: { fontWeight: "bold", fontSize: 15 },
    billingTotalValue: { color: "black" },
    paymentContainer: {
      flexDirection: "row",
      alignItems: "center",
      padding: 20,
      justifyContent: "space-between",
      backgroundColor: "white",
    },
    paymentText: { fontSize: 16, fontWeight: "600" },
    paymentDescription: { marginTop: 7, fontSize: 15 },
    placeOrderButton: {
      backgroundColor: "#fd5c63",
      padding: 10,
      width: 200,
      borderRadius: 6,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 10,
    },
    placeOrderTotal: { color: "white", fontSize: 15, fontWeight: "bold" },
    placeOrderLabel: {
      fontSize: 15,
      color: "white",
      fontWeight: "500",
      marginTop: 3,
    },
    placeOrderText: { fontSize: 16, fontWeight: "500", color: "white" },
  });
  
  const darkStyles = StyleSheet.create({
    container: { padding: 10, flex: 1, backgroundColor: "#1c1c1c" },
    header: { flexDirection: "row", alignItems: "center", gap: 8 },
    headerText: { color: "white" },
    deliveryInfo: {
      backgroundColor: "#333",
      padding: 8,
      marginTop: 15,
      borderRadius: 8,
    },
    deliveryTime: { fontWeight: "500", color: "white" },
    itemsAdded: { marginVertical: 12 },
    itemsAddedText: {
      textAlign: "center",
      letterSpacing: 3,
      fontSize: 15,
      color: "gray",
    },
    itemContainer: { backgroundColor: "#333", padding: 10 },
    itemRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginVertical: 6,
    },
    itemName: { width: 200, fontSize: 16, fontWeight: "600", color: "white" },
    quantityControl: {
      flexDirection: "row",
      paddingHorizontal: 10,
      paddingVertical: 5,
      alignItems: "center",
      borderColor: "#BEBEBE",
      borderWidth: 0.5,
      borderRadius: 10,
    },
    quantityButton: {
      fontSize: 20,
      color: "green",
      paddingHorizontal: 6,
      fontWeight: "600",
    },
    quantityText: {
      fontSize: 19,
      color: "green",
      paddingHorizontal: 8,
      fontWeight: "600",
    },
    itemPrice: { fontSize: 16, fontWeight: "bold", color: "white" },
    itemQuantity: { fontSize: 15, fontWeight: "500", color: "white" },
    deliveryInstructions: { marginVertical: 10 },
    deliveryInstructionsText: { fontSize: 16, fontWeight: "600", color: "white" },
    instructionContainer: {
      margin: 10,
      borderRadius: 10,
      padding: 10,
      backgroundColor: "#333",
    },
    instructionContent: { justifyContent: "center", alignItems: "center" },
    instructionText: {
      width: 75,
      fontSize: 13,
      color: "#ccc",
      paddingTop: 10,
      textAlign: "center",
    },
    additionalOptions: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      backgroundColor: "#333",
      paddingVertical: 10,
      paddingHorizontal: 10,
    },
    optionRow: { flexDirection: "row", alignItems: "center", gap: 6 },
    optionText: { color: "white" },
    donationContainer: {
      padding: 10,
      backgroundColor: "#333",
      marginVertical: 10,
    },
    donationRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    donationText: { color: "white" },
    donationDescription: { color: "gray" },
    donationAmount: { color: "white" },
    billingDetails: { marginVertical: 10 },
    billingDetailsText: { fontSize: 16, fontWeight: "bold", color: "white" },
    billingContainer: {
      backgroundColor: "#333",
      borderRadius: 7,
      padding: 10,
      marginTop: 14,
    },
    billingRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    billingLabel: { fontSize: 15, fontWeight: "400", color: "#ccc" },
    billingValue: { fontSize: 15, fontWeight: "400", color: "#ccc" },
    billingTotalLabel: { fontWeight: "bold", fontSize: 15, color: "white" },
    billingTotalValue: { color: "white" },
    paymentContainer: {
      flexDirection: "row",
      alignItems: "center",
      padding: 20,
      justifyContent: "space-between",
      backgroundColor: "#333",
    },
    paymentText: { fontSize: 16, fontWeight: "600", color: "white" },
    paymentDescription: { marginTop: 7, fontSize: 15, color: "white" },
    placeOrderButton: {
      backgroundColor: "#fd5c63",
      padding: 10,
      width: 200,
      borderRadius: 6,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 10,
    },
    placeOrderTotal: { color: "white", fontSize: 15, fontWeight: "bold" },
    placeOrderLabel: {
      fontSize: 15,
      color: "white",
      fontWeight: "500",
      marginTop: 3,
    },
    placeOrderText: { fontSize: 16, fontWeight: "500", color: "white" },
  });

  export default lightStyles;